### ISSUE TITLE
Not working with Node 4.2.1

### ISSUE THREAD

**Issue by mantenpanther** [garbin/elasticsearch-reindex#13]
Getting the following error:

Starting reindex in 1 shards.
/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:65
Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
worker exited with error code: 1
Reindexing completed sucessfully.

**Comment by garbin** [comment]
can you try 1.1.10？then tell me result

**Comment by mantenpanther** [comment]
sorry I lost track of node versioning lately (I upgraded from node 0.12.6 to 4.2.1). do you mean io.js 1.1.10?

**Comment by garbin** [comment]
I means elasticsearch-reindex 1.1.10

**Comment by mantenpanther** [comment]
ok, tried with 1.1.10 - still not working with following error:

events.js:397
EventEmitter.listenerCount = function(emitter, type) {
                                     ^

RangeError: Maximum call stack size exceeded
    at Function.EventEmitter.listenerCount (events.js:397:38)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:399:20)
    at Log.listenerCount (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
worker exited with error code: 1

**Comment by cpomerantz** [comment]
I was having this same issue and forced the app to use the latest async and elasticsearch modules. That appears to have fixed it for me. It's likely the elasticsearch module that needs to be updated. This is using a very old version, so there may be incompatibilities, but it should probably be updated.

**Comment by chrishiestand** [comment]
I had the same problem on another project and fixed it by upgrading `elasticsearch` to latest, 9.0.2
