### ISSUE TITLE
error when trying the custom indexer

### ISSUE THREAD

**Issue by ManuZenou** [garbin/elasticsearch-reindex#30]
Elasticsearch version: 5.3.0

```
Error: Scroll error: [illegal_argument_exception] No search type for [scan] :: {"path":"/zoe_old/impacts/_search","query":{"search_type":"scan","scroll":"1m","size":100},"body":"{}","statusCode":400,"response":"{\"error\":{\"root_cause\":[{\"type\":\"illegal_argument_exception\",\"reason\":\"No search type for [scan]\"}],\"type\":\"illegal_argument_exception\",\"reason\":\"No search type for [scan]\"},\"status\":400}"}
    at scroll_fetch (/Users/manuzenou/.nvm/versions/node/v6.9.4/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:258:15)
    at respond (/Users/manuzenou/.nvm/versions/node/v6.9.4/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:308:9)
    at checkRespForFailure (/Users/manuzenou/.nvm/versions/node/v6.9.4/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:248:7)
    at HttpConnector.<anonymous> (/Users/manuzenou/.nvm/versions/node/v6.9.4/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connectors/http.js:164:7)
    at IncomingMessage.wrapper (/Users/manuzenou/.nvm/versions/node/v6.9.4/lib/node_modules/elasticsearch-reindex/node_modules/lodash/index.js:3095:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by peter-bonanni** [comment]
I think this may be a bug with 5.* 

Still doing research but I'm not even using the custom indexer and I'm seeing this.

**Comment by tragiclifestories** [comment]
Indeed. From the [deprecation guide](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_search_changes.html#_literal_search_type_scan_literal_removed):

> The scan search type was deprecated since version 2.1.0 and is now removed. All benefits from this search type can now be achieved by doing a scroll request that sorts documents in _doc order

I will see if I can rustle up a PR.
