### ISSUE TITLE
re-index not working

### ISSUE THREAD

**Issue by sergii-rolskii** [garbin/elasticsearch-reindex#31]
**Hey, I need help. I try:**
elasticsearch-reindex -f http://localhost:9200/sms -t http://localhost:9200/sms-new
**And I have error:**
```
Starting reindex in 1 shards.
/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60
      throw new TypeError('Invalid hosts config. Expected a URL, an array of urls, a host config object, ' +
      ^

TypeError: Invalid hosts config. Expected a URL, an array of urls, a host config object, or an array of host config objects.
    at new Transport (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60:13)
    at Object.EsApiClient (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/client.js:57:22)
    at new Client (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/client.js:101:10)
    at createClient (/usr/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:194:18)
    at Object.<anonymous> (/usr/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:212:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
worker exited with error code: 1
Reindexing completed sucessfully.
```
**How can I fix it?**
**And if I try re-index with a indexer.js (include date) I have error:**
```
Starting reindex in 4 shards.
/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60
      throw new TypeError('Invalid hosts config. Expected a URL, an array of urls, a host config object, ' +
      ^

TypeError: Invalid hosts config. Expected a URL, an array of urls, a host config object, or an array of host config objects.
    at new Transport (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60:13)
    at Object.EsApiClient (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/client.js:57:22)
    at new Client (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/client.js:101:10)
    at createClient (/usr/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:194:18)
    at Object.<anonymous> (/usr/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:212:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60
      throw new TypeError('Invalid hosts config. Expected a URL, an array of urls, a host config object, ' +
      ^

TypeError: Invalid hosts config. Expected a URL, an array of urls, a host config object, or an array of host config objects.
    at new Transport (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60:13)
    at Object.EsApiClient (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/client.js:57:22)
    at new Client (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/client.js:101:10)
    at createClient (/usr/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:194:18)
    at Object.<anonymous> (/usr/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js:212:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
    at bootstrap_node.js:505:3
worker exited with error code: 1
worker exited with error code: 1
/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:60
      throw new TypeError('Invalid hosts config. Expected a URL, an array of urls, a host config object, ' +
      ^
```

**Comment by sergii-rolskii** [comment]
Any ideas?
