### ISSUE TITLE
Reindex is failing with error No living connections

### ISSUE THREAD

**Issue by debraj-manna** [garbin/elasticsearch-reindex#8]
While trying to re-index with the below command:-
```
elasticsearch-reindex -f http://172.16.84.220:9200/prod.jps.2015.07.21/ -t http://172.16.84.220:9200/
```
where 172.16.84.220 is a dedicated ES Client Node. Other than the client node ES Cluster has a dedicated master and data node.

I am seeing the below error:-
```
Elasticsearch ERROR: 2015-08-14T22:27:15Z
  Error: Request error, retrying -- getaddrinfo ENOTFOUND http
      at Log.error (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:213:60)
      at checkRespForFailure (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:192:18)
      at HttpConnector.<anonymous> (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connectors/http.js:153:7)
      at ClientRequest.wrapper (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)
      at ClientRequest.emit (events.js:107:17)
      at Socket.socketErrorListener (_http_client.js:271:9)
      at Socket.emit (events.js:107:17)
      at net.js:950:16
      at process._tickCallback (node.js:355:11)

Elasticsearch WARNING: 2015-08-14T22:27:15Z
  Unable to revive connection: http://http/

Elasticsearch WARNING: 2015-08-14T22:27:15Z
  No living connections

Reindex error: Error: No Living connections

```
Environment
- Node Version - v0.12.7
- npm Version - 2.11.3
- OS - Debian 7 - x86_64
- ES Version - 1.7.1

**Comment by garbin** [comment]
I have no cluster to test this now, But it seems like the `to_client` doesn't get right host. So I test it and try to figure out. but it works correctly. I'm using the latest version 1.1.8, which version do you use?

```
elasticsearch-reindex -f http://172.16.84.220:9200/prod.jps.2015.07.21/ -t http://172.16.84.220:92
00/
{ close: [Function],
  transport:
   { _config:
      { host: '172.16.84.220:9200',
        requestTimeout: 60000,
        apiVersion: '1.5',
        __reused: true,
        log: [Object],
        hosts: '172.16.84.220:9200',
        keepAlive: true,
        minSockets: 10,
        maxSockets: 11 },
     log: { _events: [Object] },
```

**Comment by debraj-manna** [comment]
I am using version 1.1.6
```
root@elk2:~# elasticsearch-reindex version
1.1.6
```
How can I upgrade to 1.1.8? . I have installed it as mentioned in the README 
```
npm install -g elasticsearch-reindex
```

**Comment by garbin** [comment]
```
npm install -g elasticsearch-reindex@latest
```

**Comment by garbin** [comment]
My bad, `elasticsearch-reindex version` can't get the right version number, because I forget to update the version number on the latest version. So If you've installed the latest version and the problem not been sloved, I will check again.

**Comment by debraj-manna-jabong** [comment]
Yeah I have installed the latest version.

**Comment by garbin** [comment]
There should be a file called `reindex.log` in your working dir. I want to check it.

**Comment by debraj-manna** [comment]
```
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28339,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T19:52:57.896Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28339,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T19:52:57.897Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28357,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T19:53:12.275Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28357,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T19:53:12.276Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28377,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T19:54:26.737Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28377,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T19:54:26.738Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28680,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:23:38.624Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28680,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:23:38.625Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28700,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:25:51.140Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28700,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:25:51.141Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28720,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:27:15.443Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28720,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:27:15.444Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28740,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:27:53.902Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28740,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:27:53.904Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28760,"level":50,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:29:58.938Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":143},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28760,"level":60,"err":{"message":"No Living connections","name":"Error","stack":"Error: No Living connections\n    at sendReqWithConnection (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/transport.js:171:15)\n    at next (/usr/local/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/connection_pool.js:213:7)\n    at process._tickCallback (node.js:355:11)"},"msg":"No Living connections","time":"2015-08-14T22:29:58.940Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":180},"v":0}
{"name":"elasticsearch-reindex","hostname":"elk2","pid":28938,"level":60,"msg":"worker exited with error code: 1","time":"2015-08-14T23:44:33.672Z","src":{"file":"/usr/local/lib/node_modules/elasticsearch-reindex/bin/elasticsearch-reindex.js","line":93},"v":0}
```

**Comment by garbin** [comment]
@debraj-manna I can't reproduce this error in my env. Can you try downgrade to version 1.1.6, just `npm install -g elasticsearch-reindex@1.1.6`, I think it could works. because the latest version have some improve in this part.

@drinks any idea?

**Comment by debraj-manna** [comment]
Thanks @garbin . Yeah it is working after downgrading with the command you mentioned `npm install -g elasticsearch-reindex@1.1.6`

**Comment by drinks** [comment]
Yikes will take a look.

**Comment by drinks** [comment]
Looks like this is because there's no index name on the target. I doubt I tested that use case (didn't know it was allowed). I'll work on a fix.

**Comment by debraj-manna** [comment]
@drinks - I don;t think that missing index name on the target is an issue. After downgrading to 1.1.6 the below command is working fine
```
elasticsearch-reindex -f http://172.16.84.220:9200/prod.jps.2015.07.21/ -t http://172.16.84.220:9200
```

**Comment by drinks** [comment]
@debraj-manna that's correct--I introduced the issue in the latest version by changing the way hosts are parsed out which added support for HTTPS and basic auth. It's a straightforward fix, pr coming momentarily.

**Comment by drinks** [comment]
Patch submitted, @garbin

**Comment by garbin** [comment]
@debraj-manna I've merged the hotfix @drinks submitted. So the latest version should works correctly now. I think you can give it a try.

**Comment by debraj-manna** [comment]
Yes working fine with version `1.1.9`.

**Comment by rjromay** [comment]
It's failing for me again in 1.1.11 while it's working fine with 1.1.9

**Comment by chiranjitdutta1985** [comment]
I followed the steps for downloading v 1.1.8  1.1.9 and when i reindex I get this : 

""/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:65 Log.prototype.listenerCount = function (event) {
                                       ^

RangeError: Maximum call stack size exceeded
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:65:40)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
    at Log.listenerCount (/usr/lib/node_modules/elasticsearch-reindex/node_modules/elasticsearch/src/lib/log.js:68:25)
    at Function.EventEmitter.listenerCount (events.js:442:20)
worker exited with error code: 1

What am I doing wrong ?
